name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build dev image
        run: |
          docker compose -f docker-compose.dev.yml build

      - name: Start services
        run: |
          docker compose -f docker-compose.dev.yml up -d redis app

      - name: Wait for Redis healthy
        run: |
          set -e
          for i in $(seq 1 30); do
            if [ "$(docker inspect -f '{{.State.Health.Status}}' grading-app-redis-dev)" = "healthy" ]; then
              echo "Redis is healthy"; break; fi; sleep 2; done

      - name: Run tests (pytest)
        run: |
          docker compose -f docker-compose.dev.yml exec -T app pytest

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            htmlcov
            coverage.xml

      - name: Dump service logs on failure
        if: failure()
        run: |
          docker compose -f docker-compose.dev.yml logs | sed -e 's/\x1b\[[0-9;]*m//g'

      - name: Shutdown services
        if: always()
        run: |
          docker compose -f docker-compose.dev.yml down -v --remove-orphans


