"""Add owner_id to GradingJob for multi-user support

Revision ID: 172aa1a4d8f3
Revises: 4dc77368858f
Create Date: 2025-11-15 03:22:21.486571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '172aa1a4d8f3'
down_revision = '4dc77368858f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('default_settings', sa.JSON(), nullable=True),
    sa.Column('job_structure', sa.JSON(), nullable=True),
    sa.Column('processing_rules', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('openrouter_api_key', sa.Text(), nullable=True),
    sa.Column('claude_api_key', sa.Text(), nullable=True),
    sa.Column('gemini_api_key', sa.Text(), nullable=True),
    sa.Column('openai_api_key', sa.Text(), nullable=True),
    sa.Column('nanogpt_api_key', sa.Text(), nullable=True),
    sa.Column('chutes_api_key', sa.Text(), nullable=True),
    sa.Column('zai_api_key', sa.Text(), nullable=True),
    sa.Column('zai_pricing_plan', sa.String(length=20), nullable=True),
    sa.Column('lm_studio_url', sa.String(length=500), nullable=True),
    sa.Column('ollama_url', sa.String(length=500), nullable=True),
    sa.Column('default_prompt', sa.Text(), nullable=True),
    sa.Column('openrouter_default_model', sa.String(length=200), nullable=True),
    sa.Column('claude_default_model', sa.String(length=200), nullable=True),
    sa.Column('gemini_default_model', sa.String(length=200), nullable=True),
    sa.Column('openai_default_model', sa.String(length=200), nullable=True),
    sa.Column('nanogpt_default_model', sa.String(length=200), nullable=True),
    sa.Column('chutes_default_model', sa.String(length=200), nullable=True),
    sa.Column('zai_default_model', sa.String(length=200), nullable=True),
    sa.Column('lm_studio_default_model', sa.String(length=200), nullable=True),
    sa.Column('ollama_default_model', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('configured_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marking_schemes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_marking_schemes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_prompts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)

    op.create_table('ai_provider_quotas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('limit_type', sa.String(length=20), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.Column('reset_period', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='unique_user_provider')
    )
    # AuthSession table removed (model no longer used)

    op.create_table('job_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('batch_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('models_to_compare', sa.JSON(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('batch_settings', sa.JSON(), nullable=True),
    sa.Column('auto_assign_jobs', sa.Boolean(), nullable=True),
    sa.Column('total_jobs', sa.Integer(), nullable=True),
    sa.Column('completed_jobs', sa.Integer(), nullable=True),
    sa.Column('failed_jobs', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_completion', sa.DateTime(), nullable=True),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('shared_with', sa.JSON(), nullable=True),
    sa.Column('saved_prompt_id', sa.String(length=36), nullable=True),
    sa.Column('saved_marking_scheme_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['saved_marking_scheme_id'], ['saved_marking_schemes.id'], ),
    sa.ForeignKeyConstraint(['saved_prompt_id'], ['saved_prompts.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['batch_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('models_to_compare', sa.JSON(), nullable=True),
    sa.Column('saved_prompt_id', sa.String(length=36), nullable=True),
    sa.Column('saved_marking_scheme_id', sa.String(length=36), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['saved_marking_scheme_id'], ['saved_marking_schemes.id'], ),
    sa.ForeignKeyConstraint(['saved_prompt_id'], ['saved_prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_shares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('permission_level', sa.String(length=10), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='unique_project_share')
    )
    with op.batch_alter_table('project_shares', schema=None) as batch_op:
        batch_op.create_index('idx_share_user', ['user_id'], unique=False)

    op.create_table('usage_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('tokens_consumed', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index('idx_usage_project', ['project_id'], unique=False)
        batch_op.create_index('idx_usage_user_provider_time', ['user_id', 'provider', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_user_id'), ['user_id'], unique=False)

    op.create_table('grading_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('total_submissions', sa.Integer(), nullable=True),
    sa.Column('processed_submissions', sa.Integer(), nullable=True),
    sa.Column('failed_submissions', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('models_to_compare', sa.JSON(), nullable=True),
    sa.Column('marking_scheme_id', sa.String(length=36), nullable=True),
    sa.Column('saved_prompt_id', sa.String(length=36), nullable=True),
    sa.Column('saved_marking_scheme_id', sa.String(length=36), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['job_batches.id'], ),
    sa.ForeignKeyConstraint(['marking_scheme_id'], ['marking_schemes.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['saved_marking_scheme_id'], ['saved_marking_schemes.id'], ),
    sa.ForeignKeyConstraint(['saved_prompt_id'], ['saved_prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grading_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grading_jobs_owner_id'), ['owner_id'], unique=False)

    op.create_table('submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('grade', sa.Text(), nullable=True),
    sa.Column('grade_metadata', sa.JSON(), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['grading_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('grade', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('grade_metadata', sa.JSON(), nullable=True),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_uuid', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_extension', sa.String(length=10), nullable=False),
    sa.Column('width_pixels', sa.Integer(), nullable=True),
    sa.Column('height_pixels', sa.Integer(), nullable=True),
    sa.Column('aspect_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('ocr_started_at', sa.DateTime(), nullable=True),
    sa.Column('ocr_completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('passes_quality_check', sa.Boolean(), nullable=True),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_uuid')
    )
    with op.batch_alter_table('image_submissions', schema=None) as batch_op:
        batch_op.create_index('idx_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_file_uuid', ['file_uuid'], unique=False)
        batch_op.create_index('idx_processing_status', ['processing_status'], unique=False)
        batch_op.create_index('idx_submission_id', ['submission_id'], unique=False)

    op.create_table('extracted_content',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('image_submission_id', sa.String(length=36), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('text_length', sa.Integer(), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=True),
    sa.Column('ocr_provider', sa.String(length=50), nullable=False),
    sa.Column('ocr_model', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('text_regions', sa.JSON(), nullable=True),
    sa.Column('api_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['image_submission_id'], ['image_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_submission_id')
    )
    with op.batch_alter_table('extracted_content', schema=None) as batch_op:
        batch_op.create_index('idx_confidence_score', ['confidence_score'], unique=False)
        batch_op.create_index('idx_extracted_content_image_submission', ['image_submission_id'], unique=False)
        batch_op.create_index('idx_ocr_provider', ['ocr_provider'], unique=False)

    op.create_table('image_quality_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('image_submission_id', sa.String(length=36), nullable=False),
    sa.Column('overall_quality', sa.String(length=20), nullable=False),
    sa.Column('passes_quality_check', sa.Boolean(), nullable=False),
    sa.Column('blur_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_blurry', sa.Boolean(), nullable=True),
    sa.Column('blur_threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('meets_min_resolution', sa.Boolean(), nullable=True),
    sa.Column('min_width_required', sa.Integer(), nullable=True),
    sa.Column('min_height_required', sa.Integer(), nullable=True),
    sa.Column('edge_density_top', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('edge_density_bottom', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('edge_density_left', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('edge_density_right', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_edge_density', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_edge_density', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('likely_cropped', sa.Boolean(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('assessment_duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_submission_id'], ['image_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_submission_id')
    )
    with op.batch_alter_table('image_quality_metrics', schema=None) as batch_op:
        batch_op.create_index('idx_image_quality_image_submission', ['image_submission_id'], unique=False)
        batch_op.create_index('idx_overall_quality', ['overall_quality'], unique=False)
        batch_op.create_index('idx_passes_quality_check', ['passes_quality_check'], unique=False)

    with op.batch_alter_table('scheme_criteria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_criterion_order'))
        batch_op.drop_index(batch_op.f('idx_criterion_question'))
        batch_op.drop_index(batch_op.f('ix_scheme_criteria_question_id'))

    op.drop_table('scheme_criteria')
    with op.batch_alter_table('scheme_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_question_order'))
        batch_op.drop_index(batch_op.f('idx_question_scheme'))
        batch_op.drop_index(batch_op.f('ix_scheme_questions_scheme_id'))

    op.drop_table('scheme_questions')
    with op.batch_alter_table('grading_schemes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_scheme_category'))
        batch_op.drop_index(batch_op.f('idx_scheme_name'))
        batch_op.drop_index(batch_op.f('idx_scheme_version'))
        batch_op.drop_index(batch_op.f('ix_grading_schemes_category'))
        batch_op.drop_index(batch_op.f('ix_grading_schemes_name'))

    op.drop_table('grading_schemes')
    with op.batch_alter_table('graded_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_submission_complete'))
        batch_op.drop_index(batch_op.f('idx_submission_graded_at'))
        batch_op.drop_index(batch_op.f('idx_submission_scheme'))
        batch_op.drop_index(batch_op.f('idx_submission_student'))
        batch_op.drop_index(batch_op.f('ix_graded_submissions_graded_at'))
        batch_op.drop_index(batch_op.f('ix_graded_submissions_is_complete'))
        batch_op.drop_index(batch_op.f('ix_graded_submissions_scheme_id'))
        batch_op.drop_index(batch_op.f('ix_graded_submissions_student_id'))

    op.drop_table('graded_submissions')
    with op.batch_alter_table('criterion_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_evaluation_criterion'))
        batch_op.drop_index(batch_op.f('idx_evaluation_submission'))
        batch_op.drop_index(batch_op.f('ix_criterion_evaluations_criterion_id'))
        batch_op.drop_index(batch_op.f('ix_criterion_evaluations_submission_id'))

    op.drop_table('criterion_evaluations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criterion_evaluations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('submission_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('criterion_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('points_awarded', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max_points', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('criterion_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('question_title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.CheckConstraint('points_awarded <= max_points', name=op.f('ck_points_awarded_max')),
    sa.CheckConstraint('points_awarded >= 0::numeric', name=op.f('ck_points_awarded_min')),
    sa.ForeignKeyConstraint(['criterion_id'], ['scheme_criteria.id'], name=op.f('criterion_evaluations_criterion_id_fkey')),
    sa.ForeignKeyConstraint(['submission_id'], ['graded_submissions.id'], name=op.f('criterion_evaluations_submission_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('criterion_evaluations_pkey')),
    sa.UniqueConstraint('submission_id', 'criterion_id', name=op.f('uq_evaluation_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('criterion_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_criterion_evaluations_submission_id'), ['submission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_criterion_evaluations_criterion_id'), ['criterion_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_evaluation_submission'), ['submission_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_evaluation_criterion'), ['criterion_id'], unique=False)

    op.create_table('graded_submissions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('scheme_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('scheme_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('student_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('submission_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('graded_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('graded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('evaluation_version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_points_earned', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_points_possible', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('percentage_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('scheme_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.CheckConstraint('is_complete = false OR graded_at IS NOT NULL', name=op.f('ck_complete_graded_at')),
    sa.CheckConstraint('percentage_score <= 100::numeric', name=op.f('ck_percentage_max')),
    sa.CheckConstraint('percentage_score >= 0::numeric', name=op.f('ck_percentage_min')),
    sa.CheckConstraint('total_points_earned <= total_points_possible', name=op.f('ck_points_earned_max')),
    sa.CheckConstraint('total_points_earned >= 0::numeric', name=op.f('ck_points_earned_min')),
    sa.ForeignKeyConstraint(['scheme_id'], ['grading_schemes.id'], name=op.f('graded_submissions_scheme_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('graded_submissions_pkey'))
    )
    with op.batch_alter_table('graded_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graded_submissions_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graded_submissions_scheme_id'), ['scheme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_graded_submissions_is_complete'), ['is_complete'], unique=False)
        batch_op.create_index(batch_op.f('ix_graded_submissions_graded_at'), ['graded_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_submission_student'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_submission_scheme'), ['scheme_id', 'scheme_version'], unique=False)
        batch_op.create_index(batch_op.f('idx_submission_graded_at'), ['graded_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_submission_complete'), ['is_complete'], unique=False)

    op.create_table('grading_schemes',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('total_possible_points', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_criteria', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_modified_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='grading_schemes_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('grading_schemes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grading_schemes_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_grading_schemes_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('idx_scheme_version'), ['id', 'version_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_scheme_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('idx_scheme_category'), ['category'], unique=False)

    op.create_table('scheme_questions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('scheme_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_possible_points', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.CheckConstraint('display_order > 0', name='ck_question_order'),
    sa.ForeignKeyConstraint(['scheme_id'], ['grading_schemes.id'], name='scheme_questions_scheme_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='scheme_questions_pkey'),
    sa.UniqueConstraint('scheme_id', 'display_order', name='uq_question_order', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('scheme_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheme_questions_scheme_id'), ['scheme_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_question_scheme'), ['scheme_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_question_order'), ['scheme_id', 'display_order'], unique=False)

    op.create_table('scheme_criteria',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max_points', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('display_order > 0', name=op.f('ck_criterion_order')),
    sa.CheckConstraint('max_points <= 1000::numeric', name=op.f('ck_max_points_max')),
    sa.CheckConstraint('max_points > 0::numeric', name=op.f('ck_max_points_positive')),
    sa.ForeignKeyConstraint(['question_id'], ['scheme_questions.id'], name=op.f('scheme_criteria_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('scheme_criteria_pkey')),
    sa.UniqueConstraint('question_id', 'display_order', name=op.f('uq_criterion_order'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('scheme_criteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheme_criteria_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_criterion_question'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_criterion_order'), ['question_id', 'display_order'], unique=False)

    with op.batch_alter_table('image_quality_metrics', schema=None) as batch_op:
        batch_op.drop_index('idx_passes_quality_check')
        batch_op.drop_index('idx_overall_quality')
        batch_op.drop_index('idx_image_quality_image_submission')

    op.drop_table('image_quality_metrics')
    with op.batch_alter_table('extracted_content', schema=None) as batch_op:
        batch_op.drop_index('idx_ocr_provider')
        batch_op.drop_index('idx_extracted_content_image_submission')
        batch_op.drop_index('idx_confidence_score')

    op.drop_table('extracted_content')
    with op.batch_alter_table('image_submissions', schema=None) as batch_op:
        batch_op.drop_index('idx_submission_id')
        batch_op.drop_index('idx_processing_status')
        batch_op.drop_index('idx_file_uuid')
        batch_op.drop_index('idx_created_at')

    op.drop_table('image_submissions')
    op.drop_table('grade_results')
    op.drop_table('submissions')
    with op.batch_alter_table('grading_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grading_jobs_owner_id'))

    op.drop_table('grading_jobs')
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_records_timestamp'))
        batch_op.drop_index('idx_usage_user_provider_time')
        batch_op.drop_index('idx_usage_project')

    op.drop_table('usage_records')
    with op.batch_alter_table('project_shares', schema=None) as batch_op:
        batch_op.drop_index('idx_share_user')

    op.drop_table('project_shares')
    op.drop_table('job_templates')
    op.drop_table('job_batches')
    # AuthSession table removal skipped (model removed)
    op.drop_table('ai_provider_quotas')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('saved_prompts')
    op.drop_table('saved_marking_schemes')
    op.drop_table('marking_schemes')
    op.drop_table('deployment_config')
    op.drop_table('config')
    op.drop_table('batch_templates')
    # ### end Alembic commands ###
